[package]
name = "projectpad"
version = "2.2.2"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

[build-dependencies]
reqwest = { version = "0.11.0", features = ["blocking"] }
flate2 = "1.0.20"
tar = "0.4.32"
includedir_codegen = "0.6.0"

[dependencies]
relm = "0.21.0"
relm-derive = "0.21.0"
# relm: take in a clippy fix merged after 0.20.0
# relm = { git = "https://github.com/antoyo/relm", rev = "297c7844ca20031880ac60789dee7295c52f6e7c" }
# relm-derive = { git = "https://github.com/antoyo/relm", rev = "297c7844ca20031880ac60789dee7295c52f6e7c" }
glib = "0.10.3"
gio = "0.9.1"
cairo-rs = { version = "0.9.1", features = ["png"] }
gdk = "0.13.2"
projectpadsql = { path = "../projectpadsql" }
diesel = { version = "1.4.5", features = ["sqlite"] }
pango = "0.9.1"
pulldown-cmark = { version = "0.8.0", default-features = false }
itertools = "0.10.0"
strum = "0.20.0"
chrono = "0.4.19"
includedir = "0.6.0"
phf = "0.8.0"
sourceview = "0.9.0"
serde = "1.0.123"
serde_derive = "1.0.123"
toml = "0.5.8"
dirs = "3.0.1"
keyring = "0.10.1"
serde_yaml = "0.8.17"
regex = "1.4.3"

[dependencies.gtk]
version = "0.9.2"
features = ["v3_22_29"]
